#include "freertos_tasks.h"
#include "cmsis_os.h"
#include "fatfs.h"
#include "bme280_driver.h"
#include "mpu6050_driver.h"
#include "stm32f4xx_hal.h"
#include <stdio.h>
#include <string.h>

/* External HAL handles (generated by CubeMX) */
extern I2C_HandleTypeDef hi2c1;
extern I2C_HandleTypeDef hi2c2;
extern UART_HandleTypeDef huart2;
extern CRC_HandleTypeDef hcrc;
extern IWDG_HandleTypeDef hiwdg;

/* Queue / mutex handles */
QueueHandle_t    xSensorQueue;
QueueHandle_t    xUARTQueue;
QueueHandle_t    xHealthQueue;
SemaphoreHandle_t xSDMutex;

/* Task notification handle for DMA TX complete */
static TaskHandle_t xUARTTaskHandle = NULL;

/* FatFS objects */
static FATFS fs;
static FIL   logfile;

/* ------------------------------------------------------------------ */
void RTOS_CreateAll(void) {
    xSensorQueue = xQueueCreate(10, sizeof(sensor_data_t));
    xUARTQueue   = xQueueCreate(20, sizeof(sensor_data_t));
    xHealthQueue = xQueueCreate(10, sizeof(health_token_t));
    xSDMutex     = xSemaphoreCreateMutex();

    xTaskCreate(SensorTask,   "Sensor",   512, NULL, 3, NULL);
    xTaskCreate(LoggerTask,   "Logger",   1024, NULL, 2, NULL);
    xTaskCreate(UARTTask,     "UART",     512, NULL, 2, &xUARTTaskHandle);
    xTaskCreate(WatchdogTask, "Watchdog", 256, NULL, 4, NULL);
    xTaskCreate(DisplayTask,  "Display",  512, NULL, 1, NULL);
}

/* ------------------------------------------------------------------ */
void SensorTask(void *pvParams) {
    sensor_data_t data;
    mpu6050_data_t imu;
    health_token_t tok = {.task_id = TASK_ID_SENSOR};
    TickType_t xLastWake = xTaskGetTickCount();

    for (;;) {
        /* Read BME280 */
        BME280_Read(&data.temperature, &data.humidity, &data.pressure);

        /* Read MPU-6050 */
        MPU6050_Read(&imu);
        data.accel_x = imu.accel_x;
        data.accel_y = imu.accel_y;
        data.accel_z = imu.accel_z;
        data.gyro_x  = imu.gyro_x;
        data.gyro_y  = imu.gyro_y;
        data.gyro_z  = imu.gyro_z;
        data.timestamp = HAL_GetTick();

        /* CRC32 over data fields (exclude crc field itself) */
        data.crc = HAL_CRC_Calculate(&hcrc, (uint32_t*)&data,
                                     (sizeof(sensor_data_t) - 4) / 4);

        xQueueSend(xSensorQueue, &data, 0);
        xQueueSend(xUARTQueue,   &data, 0);

        /* Report health */
        xQueueSend(xHealthQueue, &tok, 0);

        /* 1 second period */
        vTaskDelayUntil(&xLastWake, pdMS_TO_TICKS(1000));
    }
}

/* ------------------------------------------------------------------ */
void LoggerTask(void *pvParams) {
    sensor_data_t data;
    health_token_t tok = {.task_id = TASK_ID_LOGGER};
    uint8_t mounted = 0;

    /* Mount SD card */
    if (f_mount(&fs, "", 1) == FR_OK) {
        f_open(&logfile, "log.csv", FA_OPEN_APPEND | FA_WRITE | FA_READ);
        /* Write header if file is empty */
        if (f_size(&logfile) == 0) {
            f_printf(&logfile, "timestamp_ms,temp_C,humidity_pct,press_hPa,"
                               "ax,ay,az,gx,gy,gz,crc32\n");
        }
        mounted = 1;
    }

    for (;;) {
        if (xQueueReceive(xSensorQueue, &data, pdMS_TO_TICKS(2000)) == pdTRUE) {
            if (mounted && xSemaphoreTake(xSDMutex, pdMS_TO_TICKS(200)) == pdTRUE) {
                f_printf(&logfile,
                    "%lu,%.2f,%.1f,%.2f,%d,%d,%d,%d,%d,%d,%08lX\n",
                    data.timestamp,
                    data.temperature, data.humidity, data.pressure,
                    data.accel_x, data.accel_y, data.accel_z,
                    data.gyro_x,  data.gyro_y,  data.gyro_z,
                    data.crc);
                f_sync(&logfile);
                xSemaphoreGive(xSDMutex);
            }
        }
        xQueueSend(xHealthQueue, &tok, 0);
    }
}

/* ------------------------------------------------------------------ */
/* Called from HAL_UART_TxCpltCallback in main.c */
void UART_TxDoneCallback(void) {
    BaseType_t xHigherPriorityTaskWoken = pdFALSE;
    vTaskNotifyGiveFromISR(xUARTTaskHandle, &xHigherPriorityTaskWoken);
    portYIELD_FROM_ISR(xHigherPriorityTaskWoken);
}

void UARTTask(void *pvParams) {
    sensor_data_t data;
    static char buf[160];
    health_token_t tok = {.task_id = TASK_ID_UART};

    for (;;) {
        if (xQueueReceive(xUARTQueue, &data, pdMS_TO_TICKS(2000)) == pdTRUE) {
            int len = snprintf(buf, sizeof(buf),
                "{\"ts\":%lu,\"T\":%.2f,\"H\":%.1f,\"P\":%.2f,"
                "\"ax\":%d,\"ay\":%d,\"az\":%d,"
                "\"gx\":%d,\"gy\":%d,\"gz\":%d,\"crc\":\"%08lX\"}\r\n",
                data.timestamp,
                data.temperature, data.humidity, data.pressure,
                data.accel_x, data.accel_y, data.accel_z,
                data.gyro_x,  data.gyro_y,  data.gyro_z,
                data.crc);

            HAL_UART_Transmit_DMA(&huart2, (uint8_t*)buf, len);
            /* Wait for DMA complete — notified by UART_TxDoneCallback */
            ulTaskNotifyTake(pdTRUE, pdMS_TO_TICKS(100));
        }
        xQueueSend(xHealthQueue, &tok, 0);
    }
}

/* ------------------------------------------------------------------ */
void WatchdogTask(void *pvParams) {
    health_token_t tok;
    for (;;) {
        /* Receive any health token — just means at least one task is alive */
        if (xQueueReceive(xHealthQueue, &tok, pdMS_TO_TICKS(1000)) == pdTRUE) {
            HAL_IWDG_Refresh(&hiwdg);
        }
        /* If queue timeout (1000 ms): no task posted → watchdog expires → reset */
    }
}

/* ------------------------------------------------------------------ */
void DisplayTask(void *pvParams) {
    /* Placeholder — add SSD1306 calls once driver is written */
    health_token_t tok = {.task_id = TASK_ID_DISPLAY};
    for (;;) {
        /* TODO: update OLED with latest readings */
        HAL_GPIO_TogglePin(LED_STATUS_GPIO_Port, LED_STATUS_Pin);
        xQueueSend(xHealthQueue, &tok, 0);
        vTaskDelay(pdMS_TO_TICKS(500));
    }
}
